name: Auto Pack

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy README
        run: cp README.md src/
      - name: Generate Git logs
        run: git log --stat --dirstat | tee src/git.log
      - uses: actions/upload-artifact@v4
        with:
          name: Logic-Atomics
          path: src
